#!/bin/zsh
export AWS_REGION="XX"
export AWS_ACCOUNT_ID="XX"
export APP_STACK_NAME="XX"
export AWS_SUBNET_IDS="XX"
export VPC_ID="XX"
export DB_TYPE="XX"
export DB_NAME="XX"
export DB_USER="XX"
export DB_PASS="XX"
export RDS_STACK="XX"
export DB_DYNAMO_NAME="XX"