# Base image oficial de AWS Lambda para Python 3.11
FROM public.ecr.aws/lambda/python:3.11

# Copiar código de la Lambda
COPY app.py ${LAMBDA_TASK_ROOT}/
# Copiar código compartido
COPY ../../shared ${LAMBDA_TASK_ROOT}/shared

# Instalar dependencias
RUN pip install --no-cache-dir pydantic psycopg2-binary

# Comando de arranque para Lambda
CMD ["app.handler"]
