FROM nginx:stable-alpine

# Instala envsubst (viene con gettext)
RUN apk add --no-cache gettext

# Limpia el directorio por defecto
RUN rm -rf /usr/share/nginx/html/*

# Copia los archivos
COPY . /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY entrypoint.sh /entrypoint.sh

# Da permisos de ejecución al script
RUN chmod +x /entrypoint.sh

EXPOSE 80

# Usa el entrypoint personalizado
ENTRYPOINT ["/entrypoint.sh"]