AWSTemplateFormatVersion: "2010-09-09"
Description: "Crumblr -> AWS Lambda + API Gateway + PostgreSQL/DynamoDB with CORS and CloudWatch Logs"

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Target VPC

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: At least 2 subnets in different AZs
    
  DBType:
    Type: String
    Default: postgres
    AllowedValues:
      - postgres
      - dynamodb

  DBHost:
    Type: String
    Default: ""
    Description: "DB Host (only used for PostgreSQL)"

  DBName:
    Type: String
    Default: "crumblr_db"
    Description: "DB Name (only used for PostgreSQL)"

  DBUser:
    Type: String
    Default: "postgres"
    Description: "DB User (only used for PostgreSQL)"

  DBPass:
    Type: String
    NoEcho: true
    Default: "Nicololo"
    Description: "DB Password (only used for PostgreSQL)"

  DBDynamoName:
    Type: String
    Default: "crumbs"
    Description: "DynamoDB table name"

Resources:

  # ----------------- CreateCrumb Lambda -----------------
  CreateCrumbLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/create-crumb
      RetentionInDays: 14

  CreateCrumbLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: create-crumb
      PackageType: Image
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/create-crumb:latest"
      Timeout: 15
      MemorySize: 512
      Environment:
        Variables:
          DB_TYPE: !Ref DBType
          DB_HOST: !Ref DBHost
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASS: !Ref DBPass
          DB_DYNAMONAME: !Ref DBDynamoName

  # ----------------- GetCrumb Lambda -----------------
  GetCrumbLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/get-crumb
      RetentionInDays: 14

  GetCrumbLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: get-crumb
      PackageType: Image
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/get-crumb:latest"
      Timeout: 15
      MemorySize: 512
      Environment:
        Variables:
          DB_TYPE: !Ref DBType
          DB_HOST: !Ref DBHost
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASS: !Ref DBPass
          DB_DYNAMONAME: !Ref DBDynamoName

  # ----------------- GetCrumbs Lambda -----------------
  GetCrumbsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/get-crumbs
      RetentionInDays: 14

  GetCrumbsLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: get-crumbs
      PackageType: Image
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/get-crumbs:latest"
      Timeout: 15
      MemorySize: 512
      Environment:
        Variables:
          DB_TYPE: !Ref DBType
          DB_HOST: !Ref DBHost
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASS: !Ref DBPass
          DB_DYNAMONAME: !Ref DBDynamoName

  # ----------------- UpdateCrumb Lambda -----------------
  UpdateCrumbLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/update-crumb
      RetentionInDays: 14

  UpdateCrumbLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: update-crumb
      PackageType: Image
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/update-crumb:latest"
      Timeout: 15
      MemorySize: 512
      Environment:
        Variables:
          DB_TYPE: !Ref DBType
          DB_HOST: !Ref DBHost
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASS: !Ref DBPass
          DB_DYNAMONAME: !Ref DBDynamoName

  # ----------------- DeleteCrumb Lambda -----------------
  DeleteCrumbLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/delete-crumb
      RetentionInDays: 14

  DeleteCrumbLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: delete-crumb
      PackageType: Image
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/delete-crumb:latest"
      Timeout: 15
      MemorySize: 512
      Environment:
        Variables:
          DB_TYPE: !Ref DBType
          DB_HOST: !Ref DBHost
          DB_NAME: !Ref DBName
          DB_USER: !Ref DBUser
          DB_PASS: !Ref DBPass
          DB_DYNAMONAME: !Ref DBDynamoName

  # ----------------- API Gateway -----------------
  RestAPI:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: crumblr-api
      Description: "REST API for Crumblr CRUD operations"

  CrumbsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestAPI
      ParentId: !GetAtt RestAPI.RootResourceId
      PathPart: crumbs

  CrumbResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestAPI
      ParentId: !Ref CrumbsResource
      PathPart: "{id}"

  # ----------------- Lambda Permissions -----------------
  CreateLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CreateCrumbLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestAPI}/*/*/*"

  GetLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GetCrumbLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestAPI}/*/*/*"

  GetAllLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GetCrumbsLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestAPI}/*/*/*"

  UpdateLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref UpdateCrumbLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestAPI}/*/*/*"

  DeleteLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DeleteCrumbLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestAPI}/*/*/*"

  # ----------------- API Methods (AWS_PROXY) -----------------
  
  # POST /crumbs
  PostCrumbs:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestAPI
      ResourceId: !Ref CrumbsResource
      HttpMethod: POST
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateCrumbLambda.Arn}/invocations"

  # GET /crumbs
  GetCrumbs:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestAPI
      ResourceId: !Ref CrumbsResource
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetCrumbsLambda.Arn}/invocations"

  # GET /crumbs/{id}
  GetCrumb:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestAPI
      ResourceId: !Ref CrumbResource
      HttpMethod: GET
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetCrumbLambda.Arn}/invocations"

  # PUT /crumbs/{id}
  PutCrumb:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestAPI
      ResourceId: !Ref CrumbResource
      HttpMethod: PUT
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${UpdateCrumbLambda.Arn}/invocations"

  # DELETE /crumbs/{id}
  DeleteCrumb:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestAPI
      ResourceId: !Ref CrumbResource
      HttpMethod: DELETE
      AuthorizationType: NONE
      ApiKeyRequired: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DeleteCrumbLambda.Arn}/invocations"

  # OPTIONS /crumbs (CORS)
  OptionsCrumbs:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestAPI
      ResourceId: !Ref CrumbsResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      ApiKeyRequired: false
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ""
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # OPTIONS /crumbs/{id} (CORS)
  OptionsCrumb:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref RestAPI
      ResourceId: !Ref CrumbResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      ApiKeyRequired: false
      Integration:
        Type: MOCK
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ""
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true

  # ----------------- Deployment -----------------
  APIDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - PostCrumbs
      - GetCrumbs
      - GetCrumb
      - PutCrumb
      - DeleteCrumb
      - OptionsCrumbs
      - OptionsCrumb
    Properties:
      RestApiId: !Ref RestAPI

  APIStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref RestAPI
      DeploymentId: !Ref APIDeployment
      StageName: prod

  APIKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: crumblr-api-key
      Enabled: true

  UsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: crumblr-usage-plan
      ApiStages:
        - ApiId: !Ref RestAPI
          Stage: !Ref APIStage

  UsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref APIKey
      KeyType: API_KEY
      UsagePlanId: !Ref UsagePlan

Outputs:
  APIEndpoint:
    Description: "Crumblr API URL"
    Value: !Sub "https://${RestAPI}.execute-api.${AWS::Region}.amazonaws.com/prod"

  APIKeyId:
    Description: "API Key ID"
    Value: !Ref APIKey
    
  GetAPIKeyCommand:
    Description: "Command to get API Key value"
    Value: !Sub "aws apigateway get-api-key --api-key ${APIKey} --include-value --query 'value' --output text"