AWSTemplateFormatVersion: "2010-09-09"
Description: "Lambda with ECR Image"

Parameters:
  ImageName:
    Type: String
    Description: Image name

Resources:
  GetTicketsLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: get-tickets
      # PackageType: Image is mandatory for a lambda with docker loaded from ECR
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ImageName}"
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LabRole"
      # Timeout before lambda returns error in seconds
      Timeout: 300
      # Memory size in Mb
      MemorySize: 512
      Environment:
        Variables:
          DB_TYPE: postgres
          DB_NAME: XXXXXX
          DB_USER: XXXXXX
          DB_PASS: XXXXXX
          DB_HOST: XXXXXX
      Architectures:
        - arm64

  # Lambda log_group
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${TicketProcessorLambda}"
      RetentionInDays: 7

Outputs:
  LambdaArn:
    Description: ARN de la función Lambda
    Value: !GetAtt TicketProcessorLambda.Arn
